language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "tudr"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/tudr/tudr.github.io
  - REPO_TARGET_BRANCH: master

  - secure: G1sap2UiO/KBqLaGR5gwHhNuJd8RlR0Pm0yfAhGO/Djuo3d4lWoZ86GTxV6yn0HBRdKyamF6NGQ11jWthZmWAzySGqgcT6ca7QQzTLcPPwBOEvMGJtaK2q1ZZyHFpAkgopyD0vXvbX2blIY0/PqH5JgldGExZ5Enn1gHR20NNdQQkoXHHMwCPpNa2WzKklLxD+xk0x2Qtntws4lqKSrIiDh7gWa4cPZgiJGxsJ2dSqFXOMX7KE5eLuWOpjNjor1RdifMTI1fjmxMcuHZfM8/4cXiFfZ6DrlZtE7RtwDfZY4oEkn/4bEnGMM1RYIllJpjbdv0cmHgL/aHAhARx9iSonFtx6T1Wvkdm95OhXjbFg6us/xZ3sf0o+V2OJnsmd9lVSyiqAg3fRsr8gv48MIi+bLkNC1rxbJP2FS6TbzmjJxt2l/Yh6XcbWJLnsN+j/uYkHm8DL+kb8bsNt/kxkxYbUbku+EYQvyyDYVCjpBFtMgapgaeoIgDW3BN3vNfw5XITap92lFPqtI1ZSjm7VQUc0784nZ6SXJqtQfpx9FacMPZxn6g1AFiEQctTDtRcFUEDQjg11b5EvVeSaldb4/KnylOoU/cRcUzFC63160HUWmm/vvDVY9V/SUoxHIeoCa/aCFyBOi1PB0vX1GVs37GHcFfZ57DZy08P5X2y2VRCxw=

  - secure: Ln6QvHtoqZvrYSQCOmkPJTx9J6hqv9Lj4UVQ9elxQyFjCdEoSuiySqNUNh/S2KfvQxFD9zXOwb0ZY/Hn5PmizddOrE/e0X20lcZC22T8g25oOXYeXU5bqd83JstyS9qfUZFGsbWJu66+WCZikq+jeDuPmtvUKmsEaM0Su/btg3D9/SEmB+dzGFt7BFPuvDudeOI0VRoQzlzF8njAev4SAJ64hsB/HVX9yrBEiSelkXcn9KIuZY1FeOdVBb4CeeWOB3yHUo5yGjPeCCKOcCSzlH+k97wUZxyMszVYCX3sBU8US4CQMmUnu2AovsfSD2OdIoy6EAPzqRUnqrkaw+8GrMQ5JHVLR6pPVu7YSnSjjg84ENStzgF6PQihkoPYUoNJSIGx3GZ+Tu38d0UYJ3/KuvCB5DySncYwhiemDe5I9InfM50QgbYipAXSLgn7Ak+y6LeFUYjPytE2Wq+BZ1X8gndNy1Cno9EiUI++OPJZWg3SopCuog45vGxVoj/h7nuA6z1d40dc7rOHjCXnV+oKX2KauToM75pNeD2an8zMs9iZsjFUg5PPJKOwZUJbtp337fHUw5/b5jgfAt96KKgqrLmQKbag5hKwEcyqKBCQzzjMnvlcB8+iAUsHiKnTRXs1dTwE+GaYZYwqtyYAnvBMveNfzuP9aGeo6akA5Xk9+xY=
