# Exclude these files from production site
exclude:
   - Gemfile
   - Gemfile.lock
   - LICENSE
   - README.md
   - CNAME
   - Vagrantfile

name: Tudor Saitoc
markdown: kramdown
pygments: true
permalink: /:year/:month/:title/
url: tudr.github.io
author:
    name: Tudor Saitoc
#    twitter: @tudorsnyc
