# protfolio generator
portfolio_dir: "projects"
related_project_keys: ["category": "technology"]
related_min_common: 0.7
  # "category": project",...  "sales", "growth", "saas", "lifehack", "book", "article", "tutorial", "playbook", "data", "ai", "recommended"]

# Exclude these files from production site
exclude:
   - Gemfile
   - Gemfile.lock
   - LICENSE
   - README.md
   - CNAME
   - Vagrantfile


# Site settings
title:       "return of the kid"  
email:       tudor@saitoc.me
author:      Tudor Saitoc
description: "community supported personal and professional growth"

# base GitHub page (http://username.github.io):
# url: "http://username.github.io"
# baseurl: ""

# GitHub project pages:
# url: "http://username.github.io/projectname"
# baseurl: "/projectname"

# url:         "http://tudr.github.io"
# baseurl:     ""

url:         "http://127.0.0.1:4000"
baseurl:     ""

date_format: "%b %-d, %Y"
timezone: America/New_York


# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tudr

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 

# Social icons
github_username: tudr
bitbucket_username:
stackoverflow_id:
twitter_username:  tudorsnyc
skype_username: tsaitoc
steam_nickname:
google_plus_id: tudor@saitoc.me
linkedin_username: tudorsnyc
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
# redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-auto-image
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]


