# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
url: "http://tudr.github.io"
baseurl: "tudr"

# If you are building a GitHub project page then use these settings:
#url: "http://tudr.github.io/tudr"
#baseurl: "/tudr"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: the kid works hard

# Short description of your site
description: a new approach to project completion for business functions

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "https://avatars2.githubusercontent.com/u/15084114?v=3&s=96"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Planning: "Roadmap"
  Website: "http://achievr.us"
  
# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Tudor Saitoc
  email: "tudor@saitoc.me"
  github: tudr    # eg. daattali
  twitter: tudorsnyc   # eg. daattali
  linkedin: tudorsnyc  # eg. "pub/dean-attali/8/946/143"
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: true
  github: true
  linkedin: true
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "tudr.co"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/New York"
markdown: kramdown
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
