---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: author
  label: author
- type: field_group
  name: navbar-links
  label: navbar-links
  fields:
  - type: text
    name: Popular
    label: Popular
  - type: text
    name: Recommendations
    label: Recommendations
  - type: field_group_list
    name: Connect
    label: Connect
    fields:
    - type: text
      name: About me
      label: About me
- type: file
  name: avatar
  label: avatar
- type: boolean
  name: round-avatar
  label: round-avatar
- type: field_group
  name: social-network-links
  label: social-network-links
  fields:
  - type: text
    name: email
    label: email
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: boolean
    name: rss
    label: rss
- type: field_group
  name: share-links-active
  label: share-links-active
  fields:
  - type: boolean
    name: twitter
    label: twitter
  - type: boolean
    name: facebook
    label: facebook
  - type: boolean
    name: vk
    label: vk
- type: text
  name: url-pretty
  label: url-pretty
- type: boolean
  name: link-tags
  label: link-tags
- type: number
  name: excerpt_length
  label: excerpt_length
- type: text
  name: navbar-col
  label: navbar-col
- type: text
  name: navbar-text-col
  label: navbar-text-col
- type: text
  name: navbar-border-col
  label: navbar-border-col
- type: text
  name: page-col
  label: page-col
- type: text
  name: text-col
  label: text-col
- type: text
  name: link-col
  label: link-col
- type: text
  name: hover-col
  label: hover-col
- type: text
  name: footer-col
  label: footer-col
- type: text
  name: footer-text-col
  label: footer-text-col
- type: text
  name: footer-link-col
  label: footer-link-col
- type: text
  name: title-separator
  label: title-separator
- type: text
  name: date_format
  label: date_format
- type: text
  name: timezone
  label: timezone
- type: text
  name: markdown
  label: markdown
- type: text
  name: highlighter
  label: highlighter
- type: text
  name: permalink
  label: permalink
- type: number
  name: paginate
  label: paginate
- type: field_group
  name: kramdown
  label: kramdown
  fields:
  - type: text
    name: input
    label: input
- type: field_group_list
  name: defaults
  label: defaults
  fields:
  - type: field_group
    name: scope
    label: scope
    fields:
    - type: text
      name: path
      label: path
    - type: text
      name: type
      label: type
  - type: field_group
    name: values
    label: values
    fields:
    - type: text
      name: layout
      label: layout
    - type: boolean
      name: comments
      label: comments
    - type: boolean
      name: social-share
      label: social-share
    - type: boolean
      name: readtime
      label: readtime
- type: list
  name: exclude
  label: exclude
- type: list
  name: plugins
  label: plugins
